### ISSUE TITLE
Aligned to 256K buffer size

### ISSUE THREAD

**Issue by Jakub6** [lyusupov/ADSB-Out#5]
Hello, 

could you please explain me, why are you doing aligned to 256K buffer size?
# "dd if=Samples.iq8s of=Samples_256K.iq8s bs=4k seek=63"

It seems to me, just adding zeros to the signal, but if I change it, it doesnt work.

Thanks,

Jakub

**Comment by lyusupov** [comment]
Ask this question to [HackRF](https://github.com/mossmann/hackrf) author.
